language: node_js
node_js:
 - "8"

script:
 - npm run lint
 - npm run build

deploy:
  skip_cleanup: true
  provider: cloudfoundry
  username: $CF_USERNAME
  password: $CF_PASSWORD
  api: https://api.run.pcfbeta.io
  organization: pivot-jsharpe
  space: code-your-future
