language: node_js
node_js:
- '8'
script:
- npm run lint
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: gwvBqR2RE/Mrm8RTibb/XCG1Ve0puBSy00tUItGr6hG7O+GEjYZQSzABQZ7w/vjN3h9yFYUyz27beaHbsHrGUfB1Eo/YPJ6S6Wymfzh8yZ//ECXpfzjlaVaVKEj2rhuOTUefw54K8B0ld/mqgw0oBYNxL3DUB9HxMuEkcTcJWW27ZwbgB6dkO71eoIhu4z4z3ROJc3vqJwSeYqxcP4nyIJIR4FzTmdIMNxVzYh05hwhXj7IBmupmdL2hcdD4opBlO++pJZBSMlCuynRqTin5Fj06pBp7FcWLdkLdyC68pAtvDUPkK8YPPzG522sMjj+eiBqTGwoELCGYlAOtz6bSpk/X2uAqhF13Elwq+VHEzocneeOxKYuUO9dDXBkRJVLMeIR3yz+RuHpq/yQl8wicAe4USRBEcNVjYFWbRej0MzDnAPJYTqAGykVr1tQTCeGx9HLVzCplWPy7N9hU+ab1VsFYQjmp/7Ax1DFob98Co9RRNEpMOYnjwj+9EDen523CgrcKZC2tSiF8L1UE6qlUFBLbmjGaNZ1PHLt/ACgh+3txngD+EQLYz7cJT/UBooymcNca2/Og/SE/cvhJwLgID9j0k+ftdzcFcR5u+0ADM2l+MLFZf5pYL3h8wvGtJWH6rFN96HbVLlu+Yd7Jg30tN/KRamHc3z1iZcKWy/L4Mys=

